source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'OpenKuiklyIOSRender' , '~> 2.6.0'
  pod 'easyui', :path => '../easyui'

  pod 'SDWebImage'
end